### ISSUE TITLE
Force a choice between null and default value

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#1059]
This is related to https://github.com/zikula/core/issues/3590, using MySQL 5.7, where values must be supplied for columns unless null values are allowed.

In the MOST UI (or validator?) each field needs to be set to allow NULL, OR a default value needs to be provided.

**Comment by craigh** [comment]
There is a Null to empty transformer in the Core Bundle if needed.

**Comment by Guite** [comment]
I don't understand the issue, please elaborate.

The generator uses the specified default value if given.
If there isn't one it uses nullable (if the field has set `nullable=true`) or a reasonable fallback value (e.g. an empty string).

Earlier it also cared for setting default values even if they were not set. But you didn't like that, see #945.

**Comment by robbrandt** [comment]
That was before I knew MySQL 5.7 forced the issue. :( Sorry.

The issue is that in MySQL 5.7 if you do an insert that doesn't address all columns in a table, the columns not addressed must either 1) allow null, or 2) have a default value set.  My suggestion for MOST is that the UI or validation during "generate" mimic this logic.

I'll give you an example.  Say in MOST you've created an entity that has 4 string fields string1, string2, string3 and string4, and you have NOT ticked the nullable box nor have you provided a default value.   If you create a custom form that only fills in string1 and string2, the insert will eventually get translated into something like INSERT INTO my_entity (string1, string2) VALUES ('value1', 'value2');.  This will fail because string3 and string4 do not have values provided, are not nullable and no default value is set.

**Comment by Guite** [comment]
So you suggest that validation should enforce that all fields are either nullable or have a default value set or are mandatory (so the form requires an input value). Is that correct?

**Comment by Guite** [comment]
ping @robbrandt

**Comment by Guite** [comment]
I think there is nothing general to do here.
The generator uses a default value if one is given, otherwise it defaults to a default value (like 0 or an empty string) or to null, depending on whether nullable is true or false. Details at https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/models/entity/Property.xtend#L148

Closing. Feel free to create another issue if you experience any related problem with a concrete use case.
