### ISSUE TITLE
Not able to create item

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1078]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK14
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
After entering dates and click submit button, the item should be saved into the DB.

### Actual behavior
I get a redirect to the edit template without any feedback, this concerns the 2 entities album ( selfrelation 1:n) and pictures ( 1:n relation with albums). The entity avatars is not concerned.

### Steps to reproduce
Take a fresh generated module version of 'Image' and try to create an album or a picture.

**Comment by craigh** [comment]
are categories involved?

**Comment by Guite** [comment]
Probably not (but not sure yet):

- `album` (not working) is categorisable
- `picture` (not working) is not categorisable
- `avatar` (working) is not categorisable

**Comment by Portugao** [comment]
Yes, correct.

**Comment by Guite** [comment]
@Portugao the problem is in your model configuration: both the `album` and the `picture` entities contain a mandatory integer field named `pos`. These fields have a default value of `0` which are not valid for a mandatory field. But at the same time these fields are set to `visible false` so they are hidden in the editing forms which causes that also the error is not visible.
Closing as won't fix.

**Comment by Guite** [comment]
Some possible options for you:

- change the default value to 1
- make the fields visible again
- set the fields programmatically for new entities so they have a valid value during creation

**Comment by Portugao** [comment]
👍 
Thx.
