### ISSUE TITLE
Redirect after creating item does not get completed, because of calling list of posts does not work

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1079]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15DEV
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.30

### Expected behavior

After creating an item get redirected to post overview in admin area.

### Actual behavior
```
SELECT COUNT( DISTINCT m0_.id ) AS sclr_0
FROM mu_blogging_post m0_
LEFT JOIN mu_blogging_post m16_ ON
```
This query get not completed and blocks the database.
Seems to relate to https://github.com/Guite/MostGenerator/issues/1078

### Steps to reproduce
Take the actual repository form github of blogging module and try to create an item.

**Comment by Guite** [comment]
Sorry I can not do anything about this. The count query is executed by Doctrine paginator. And it is very expensive because your posts entity contains 14 translatable fields (which means 14 joins). And in addition there is a self relation which causes another 14 joins and another 14 joins and another 14 joins ...

removing the self relationship and replace it by a cheap integer field (like `linkedPostId`). Then you can query the linked post only at those places where you really need it.
