### ISSUE TITLE
Idea: Template/Form Constructor

### ISSUE THREAD

**Issue by KratorD** [Guite/MostGenerator#1178]
It could be interesting a tool in MOST for customize template/form in order to design more that programming. The tool can be similar to this:
![imagen](https://user-images.githubusercontent.com/5812569/34245324-c0a2dc76-e629-11e7-88a7-f1e9830463f5.png)

It's an example. 
In the left panel, you can see "folders". This folders can be entities and under them, each field of the entity.
In central panel, you can add your fields (with a button or drag and drop...) and "construct" you template/form
In right panel, you can adjust properties for each field. For example (most important IMO), define the width (you can see in the image that the space is "limit" for columns with letters (A,B,C...))

Can this tool be built to MOST? Opinions? (yes, i know that it's hard...)

**Comment by Guite** [comment]
Modeling of views has been dropped from the roadmap because with this the modeling process would become too detailed and we would loose the benefits of having a more abstract level. A model should be concise.

So :-1: from me.

See also https://github.com/Guite/MostGenerator/issues/564 which is about introducing groups for fields. With these it would also become easier to create and arrange fieldsets in edit forms.
