### ISSUE TITLE
Submitting new content with 'Edit Access' only

### ISSUE THREAD

**Issue by DirkThiele** [Guite/MostGenerator#1195]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.3.2/latest git/etc]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.7]
| PHP Version            | [PHP 5.6.36-nmm1]

### Expected behavior
User with `Edit Access` should not be able to create new content.
`Comment Access` normally should be enough for editing existing content.

### Actual behavior
Currently with `Edit Access` the user can already submit new content even if he is not able to `Submit and Approve`.

### Permissions
Component: `YourModule:YourEntity:`
Instance: `::`
Level: `Edit Access`

### UPDATE
If the user group gets `Add access` it is also possible for them to edit content from other users, even if the MOST settings have been set to "Owner gets permission"

The above mentioned permission comes right after the admin permission and is the only one that has been added after the installation of Zikula

**Comment by DirkThiele** [comment]
Please read the Update at the end of my writing

**Comment by Guite** [comment]
Note: this issue is about entities with `ownerPermission=true`.

**Comment by Guite** [comment]
@DirkThiele I think this is expected behaviour.

Without `ownerPermission` one needs `ACCESS_ADD` to create new content and `ACCESS_EDIT` to edit existing content.

With `ownerPermission` one needs `ACCESS_ADD` to submit and approve new content, `ACCESS_EDIT` to edit existing (own) content and `ACCESS_COMMENT` to submit (without approval) new content. So a user without `ADD` can create new content, defer it, update it and finally submit it. But he has no control about whether it will be approved or not.

Can you please explain what you would like to have changed and for which reason?

**Comment by Guite** [comment]
Oh I think I've found the problem.

@DirkThiele can you please test the following: in the _view_ template of your entity search for `{% if canBeCreated %}`. After that there is a permission check for the link to the page for creating a new entity. Does it check for `ACCESS_EDIT`? If yes, change that to `ACCESS_COMMENT` and see if you can submit new entries with only _comment_ rights with this.

**Comment by DirkThiele** [comment]
I will check, when I'm back from vacation and let you know.

**Comment by Guite** [comment]
> A user with EDIT ACCES only & ownerPermission=true should be able to edit just one single entry that has been created by the Administrator and at the same time he should not be able to add any further.

If I understand you correctly you can just give those users edit access and remove the creation link. In case somebody nevertheless finds out the creation URL and submits something, you can just reject it instead of approving it.

I do not see any requirement (yet) for doing a general change in the generator. Because in most use cases one wants users being able to submit new stuff. So your requirement is rather rare and should be done as part of customisation I think.
Any other opinions @gfr @portugao @rallek ?

> To me it would make sense if MODERATION ACCESS comes AFTER ADD ACCESS

I agree, but historically moderate is less than edit or add. See here: https://github.com/zikula/core/blob/2.0/src/lib/Zikula/Bundle/CoreBundle/HttpKernel/ZikulaKernel.php#L27-L35 Not easy to change without breaking existing stuff.

**Comment by Portugao** [comment]
I think we should talk in German on Slack, because i'm not sure i understand everything completely.

**Comment by Guite** [comment]
>> To me it would make sense if MODERATION ACCESS comes AFTER ADD ACCESS

> I agree

This is why I never use MODERATE for anything (simply because it is so confusing as one always thinks it would be "more" than edit/add).

**Comment by DirkThiele** [comment]
To me it looks like you simply would have to change the order and values in ZikulaKernel.php
but if you say its too difficult ... of course you know this much better than me.

**Comment by DirkThiele** [comment]
I see it is a big issue but isn't it worth to align the permission structure to what is being generated by MOST for example?

Inside the modules it is called "Submit" or "Submit and Approve" and the permissions are called "Edit access" or "Add access".

To me "Submit and approve" and also "Defer" is a moderator's job that should require a higher permission level than "Add access".

Maybe it is not a high priority thing but if you ask me, it would help a lot to have the same wording and meaning.

**Comment by Guite** [comment]
> To me "Submit and approve" and also "Defer" is a moderator's job that should require a higher permission level than "Add access".

Defer is a personal action: if I want to put more work into my draft before submitting it I can defer it and continue editing it later.
About approval: there is nothing between "add" and "admin" - except "delete".

> I see it is a big issue but isn't it worth to align the permission structure

This would be a core issue and a BC break. Definitely not job of the generator.

**Comment by DirkThiele** [comment]
OK, Topic closed then.
