### ISSUE TITLE
No translation datas saved

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1210]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows 10
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.11
| PHP Version            | 7.1

### Expected behavior
Saving english datas, default language german.

### Actual behavior
If I create an entity, there are only the german datas saved into the database. Also editing has no effect.

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

[TestApp3.zip](https://github.com/Guite/MostGenerator/files/2526737/TestApp3.zip)

**Comment by Guite** [comment]
Odd... doesn't this work with several other modules, too? Like News, Blogging, Content, etc.?

**Comment by Portugao** [comment]
I created this testapp, because I have pager problems or something else with MU/Blogging; To rule out that my own code is causing the problems. The pager problem is also in this TestApp...
Something seems to be wrong?!

**Comment by Guite** [comment]
pager problem? I thought this issue was about something with translations?

**Comment by Portugao** [comment]
Yes, this is about translation.

**Comment by Portugao** [comment]
Indeed very strange.

**Comment by Guite** [comment]
This works fine for me.

Here is what I did:

1. Create article using *German* language with this initial data:
  - German start text: `Artikel 1`
  - English start text: `No 1`
  - Result: start text is shown correctly in both languages
2. Edit the article using *German* language and change:
  - German start text: `Artikel 123`
  - English start text: `No 123`
  - Result: start text is shown correctly in both languages
3. Edit the article using *English* language and change:
  - German main text: `Haus`
  - English main text: `House`
  - Result: main text is shown correctly in both languages

Please re-do these steps and see whether it works for you.
Is it possible that you confused non-translatable fields with translatable fields? This occured to me because I first thought that translation would not properly work for the title until I realised the title isn't translatable at all.

**Comment by Portugao** [comment]
Hi Axel, it seems, that it is necessary to call the other language once to work with it.
Now it works. Close it.
