### ISSUE TITLE
Dates are not shown

### ISSUE THREAD

**Issue by KratorD** [Guite/MostGenerator#1259]
### Expected behaviour - What did you expect to happen?

```bash
Date is showed in Views and Details views
```

### Current behavior - What happened instead?

```bash
Date is not showed
```

### Steps to reproduce

```bash
1. Create a record in your app
2. Navigate to View o Display
3. Review dates fields
4. Date is not showed
```

### ModuleStudio version

latest git

### Operating system

Windows

### Zikula target in model

ZK30

### Zikula version

3.0.x

### PHP version

7.3.x

**Comment by Guite** [comment]
Works fine on my local host (using Kubuntu 21.10 / Zikula 3.1.0-DEV / Symfony 5.3.9 / PHP 8.0.8).

![image](https://user-images.githubusercontent.com/277531/138339049-ba79c7d3-9f7c-4204-91e4-1cdedd09f2b6.png)


1. Please ensure you have the latest staging version. You should get another staging update in about 30 minutes, since I've just commited a minor patch to the Git main branch.
2. Is it possible that you do not have the PHP extension "intl" installed and are using a locale other than `en`? In this case the Symfony intl polyfill is used as a fallback which supports only English. So please ensure the native PHP extension is installed and available.
3. You can also try a common module, like Content or (the rather simple) MultiHook so see if it works there.

**Comment by KratorD** [comment]
Hi again.

Thanks Guite, I haven't activated the intl. I have modified the php.ini and now it's working. 
Thanks.
