### ISSUE TITLE
Too long option explanations are truncated.

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#335]
As you see at the bottom of the picture, the explanation is truncated in the middle.
![image](https://f.cloud.github.com/assets/2145092/753081/33ac1c5c-e55b-11e2-930a-ecd19c419c01.png)

Ubuntu 13.4, MOST 0.6.0

**Comment by Guite** [comment]
This is fixed in 0.7.0. Instead of the status line explanations are now shown in tooltips of question mark icons offered by the new properties view. These tooltips contain strings which automatically use multiple lines for longer texts.

See this screenshot:

![screenshot_20161213_201035](https://cloud.githubusercontent.com/assets/277531/21154896/5ad624fe-c170-11e6-9859-a62450e36ae8.png)
