### ISSUE TITLE
Implement new composer spec

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#707]
https://github.com/zikula/core/blob/186dee19c8e28a762ae01cd54fb44689872ec131/src/system/MailerModule/composer.json#L20

**Comment by craigh** [comment]
This should be expanded to match the entire new `composer.json` spec. 

https://github.com/zikula/SpecModule/blob/master/composer.json
https://github.com/zikula/SpecModule/blob/master/composer.md

I only added the `url` in those cases because the /system modules are not yet final in development but this was a good solution at the moment.

**Comment by Guite** [comment]
Thanks for elaborating - added the `feature` label accordingly :smile:

**Comment by craigh** [comment]
also - with the implementation of the new `composer.json` spec, the old `Version` class should be removed.

**Comment by Guite** [comment]
Also #708 should be done in the same step.

**Comment by Guite** [comment]
Done in b8853a9c51b58553c60cc729dff26be02354369c except app dependencies reported in https://github.com/zikula/core/issues/2640
