### ISSUE TITLE
[1.4.x]  Class 'Zikula\Core\AbstractExtensionInstaller' not found if i try to install

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#719]
I do not know if this is an issue of MOST!?

```
Fatal error: Class 'Zikula\Core\AbstractExtensionInstaller' not found in ´domain/modules/mu/eternizer-module/Base/EternizerModuleInstaller.php on line 28
```

**Comment by craigh** [comment]
most implemented the feature before it is even available in the core! you have to wait until this branch is pulled into the core:

https://github.com/zikula/core/tree/BlockApi

**Comment by Portugao** [comment]
Thx Craig for your reply.

**Comment by Guite** [comment]
Yes I was a bit overzealous, since I did not notice that this change went into the BlockApi branch instead of the 1.4 branch.
You have three options:

1. Wait until the branch has been merge, like Craig suggested.
2. Revert a420cee54c8273ac5250517a0c37c066f7330bfb on your generated installer base class.
3. Use the BlockApi branch for your development site.
