### ISSUE TITLE
Move item actions out of Entity classes

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#727]
Item actions should not be determined inside the entity.
Instead use either a dedicated helper class or the LinkContainer.

Users module does this:

* https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Helper/AdministrationActionsHelper.php
* https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Controller/UserAdministrationController.php#L86
* https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Resources/views/UserAdministration/userlist.html.twig#L30

**Comment by craigh** [comment]
I've been working on a different implementation of this and would now discourage moving action items into a twig extension.

I have one implementation now which uses a `Helper` class to create the "actions" content. This helper class is then injected into the template and used like:

    {{ myActionsHelper.show(item) }}

this is fine so far, but I may go even further with this idea. Since the Actions are simply a collection of links, it begins to make sense to add them to the LinkContainer class and then recall them from there. I haven't worked this out in detail in my head yet but I think it is a promising idea.

Additionally, I now dislike the use of Twig extension for this task as it "litters" the Twig namespace with many "one time use" functions that probably shouldn't be there as they are too specific in their usage.

**Comment by Guite** [comment]
Note: `system/UsersModule/Helper/AdministrationActionsHelper.php`

**Comment by Guite** [comment]
From #624:

> Item actions should not rely on url arguments.
> In the Routes module the RouteEntity can be loaded before the MOST module is called.
> This causes the item actions to be prepared (as the method is called in the postLoad subscriber).
> Later, when the MOST module is actually displaying the items, it does not recalculate them
> (but it should!) and doesn't display the correct actions.

**Comment by Guite** [comment]
> I haven't worked this out in detail in my head yet but I think it is a promising idea.

@craigh What is your current thinking about it?

**Comment by craigh** [comment]
I think I prefer the LinkContainer but some refactoring or new implementation would be needed as item actions require an argument.I haven't worked on it since April

**Comment by Guite** [comment]
> some refactoring or new implementation would be needed as item actions require an argument.

Why? Couldn't the link container just used as the action helper, too? Like `$linkContainer->generateEntityActionsFor($myEntity)`

**Comment by craigh** [comment]
currently the [LinkContainerInterface](https://github.com/zikula/core/blob/ce9260a54d368a13351dc9a915f36313ef2df7c7/src/lib/Zikula/Core/LinkContainer/LinkContainerInterface.php) has only two methods and only one intended for public use: `getLinks($type)` so, while your suggestion is possible, it would fall in to the category of a new implementation 😄

**Comment by craigh** [comment]
my initial thought was to refactor and do something like `getLinks($type, $args = null)` and then a new type of `actions` could be added. This would be BC with existing types (like `admin`, `user`, `account`) and also allow for further expansion.

**Comment by Guite** [comment]
Done in 6505ea49302fee35c225f4f3d1b35d32aa6763f7
