### ISSUE TITLE
[1.4.x] Missing files

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#735]
It seems, the generator does not generate completely.
So i miss the MUImageModuleVersion.php in base folder and all the files of the base folder in the root of the module.

I tried online and offline.

Maybe I'm wrong. Don't know...

**Comment by Guite** [comment]
The version class does not exist in 1.4/2.0 modules anymore. The module meta information now lives in `composer.json`.
In the base folder there are five files: `MUImageEvents.php`, `MUImageModuleInstaller.php`, `MUMUImageModule.php`, `UploadHandler.php`, `bootstrap.php`.
No concrete subclasses (non-base files) are generated though which is caused by the `generateOnlyBaseClasses true` setting in your model.

Feel free to reopen if you have additional questions about this.
