### ISSUE TITLE
[1.4.x] Trying to install failed

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#738]
1.4.3 build 31
I get this error message now:

```
You have requested a non-existent service "mumuimagemodule.controller_helper".
```
I tried different names of folders...

**Comment by Guite** [comment]
This is weird, because it should be named `mu_muimage_module.controller_helper` (including underscores). Can you search through the files checking where `mumuimagemodule.controller_helper` occurs?

**Comment by Portugao** [comment]
Very weird. I looked through the files and do not have any idea where to find it.

**Comment by Portugao** [comment]
The error comes from the install method, where i find:

```
        try {
            $controllerHelper = $this->container->get('mumuimagemodule.controller_helper');
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $e->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => UserUtil::getVar('uname'), 'errorMessage' => $e->getMessage()]);
        
            return false;
        }

```

**Comment by Guite** [comment]
You are using an obsolete version. You probably regenerated from MOST and not using the webgen, right? Please enable the staging updates in the MOST preferences. Afterwards restart ModuleStudio. It should then automatically install the latest updates. The restart will fail with a popup message showing an error, because also the included Java has been updated. Then start ModuleStudio again and regenerate the application. Now the `install` method should contain `$this->container->get('mu_muimage_module.controller_helper');`.

**Comment by Portugao** [comment]
Strange. Updated MOST offline. Regenerated the module.
```
You have requested a non-existent service "mu_muimage_module.controller_helper".
```
Tried with webgen the same...

**Comment by Guite** [comment]
Okay, I will fix this.

**Comment by Portugao** [comment]
Thx a lot. Wish to get a look into Zikula 1.4.x. :smile:

**Comment by Guite** [comment]
Fixed in https://github.com/Guite/MostGenerator/compare/f0a6d54d62afa0ed366cd34938ee4bf366a2ea17...04ebf502adc25e930ea9b4e970f319cb4f526e17
The webgen will be updated in about 20 minutes. About 10 minutes later the update should also arrive at ModuleStudio.

**Comment by Guite** [comment]
If you experience further errors please create new issues for them. Thanks.
