### ISSUE TITLE
Currency field, update requires editing the value

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#843]
Using 0.7.0 beta 2, targeting ZK136.

I have a decimal field with the Currency property set.  I submitted a form where the value was entered as 2500, successfully.  When I tried to edit the existing record, the value was displayed as 2,500.00, and an error message stated "Please enter a valid number in this field.".  I tried submitting the form without editing, and (rightly so!) nothing happened.  I removed the comma and was able to submit.  But you shouldn't have to do that...

**Comment by Guite** [comment]
I suspect this is a problem in the old Form component in the core, because the module just assigns the field value to the formdateinput plugin.
For testing you can try removing `DataUtil::formatForDisplay` here: https://github.com/zikula/core/blob/1.3/src/lib/Zikula/Form/Plugin/DateInput.php#L219
Another workaround would be removing the comma in the `locale.ini` file: https://github.com/zikula/core/blob/1.3/src/locale/en/locale.ini#L6

**Comment by Guite** [comment]
ping @robbrandt

**Comment by Guite** [comment]
Closed as `won't fix`.
