### ISSUE TITLE
permission problems with own items

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#922]
I do not know if I am using the permissions in the right way.

My problem: I do have a module with the setting to create own items. Creating own items is only possible with the permission "edit". But if I grant edit permissions the user is also able to add items to other useres items. (e.g. vehicles do have vehicleImages, the user can add own vehicleImages to others users vehicle).

What is the right way for the permissions to let a user create own items and relation items?

**Comment by rallek** [comment]
later I have switched back the permission level to comment. Now the user can only add related items (vehicleImages) to the own item (vehicle). But now he is not able to add another vehicle item

**Comment by Guite** [comment]
At the moment the `ownerPermission` setting is used for creating/editing the entities only. This means that currently it is not considered for any relationships yet.
So this issue is basically about enhancing relationship handling accordingly.

So if 1 person has n addresses we should:

- Show only an *add address* link for admins and owners of a person.
- Filter the person list to own persons for non-admins on the address editing/creation page.

Do you agree with this proposal?

**Comment by rallek** [comment]
sounds good!

**Comment by robbrandt** [comment]
👍 thumbs
