### ISSUE TITLE
Support entity-specific workflow xml files

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#961]
I have a fairly simple module that has 2 entities, both are "enterprise" workflows.

However both entities require some customization on their workflows, in different ways.  So they each need to have their own enterprise.xml file.

I would propose that each entity should have it's own copy of the xml file, stored in a folder named for the entity it belongs to, much like template files are stored.

For a workaround for my current module I am thinking I will change the simplest workflow to a "standard" workflow, and customize standard.xml to be more like enterprise.xml.

**Comment by Guite** [comment]
Can you please test whether the old workflow system supports xml files in subfolders?
If not this needs to wait for https://github.com/zikula/core/issues/2423

**Comment by robbrandt** [comment]
No it does not.

**Comment by Guite** [comment]
By "old" I mean the traditional workflow system which is not based on the Symfony workflow component yet ;-)

**Comment by Guite** [comment]
Until this is done you can copy the xml file and override `WorkflowHelper#getWorkflowName` like this:

```
    public function getWorkflowName($objectType = '')
    {
        if ($objectType == 'myEntity') {
            return 'special';
        }

        return parent::getWorkflowName($objectType);
    }
```

**Comment by Guite** [comment]
Closing this as _won't fix_ because it looks not reasonable to generate identical files multiple times. With the new workflow system you can easily copy and customise workflows (either manually or using the new UI-driven workflow editor). Also you can even store your custom workflows in `app/Resources/workflows/` instead of `modules/Acme/YourModule/Resources/workflows/`. Note the `getWorkflowName()` method mentioned above is not used anymore with that. Instead a workflow itself specifies which entities it supports.

**Comment by Guite** [comment]
Reopening because if one entity has a special state (like `deferred`) this should not be applied to other entities.

**Comment by Guite** [comment]
Wrong alert: WorkflowHelper dynamically filters the available actions depending on the entity type.
